/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod'
import * as generated from './schema'
export type Json = z.infer<typeof generated.jsonSchema>
